version: '3'
services:
  product-service:
    build: product-service
    expose:
      - "3001"

  review-service:
    build: review-service
    expose:
      - "3002"

  nginx:
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - product-service
      - review-service
